import { useDispatch } from "react-redux";
import { useRouter } from "next/router";
import { login, logout, fetchUserTodo } from "@features/userSlice";
import { Col, Container, Form, Row } from "react-bootstrap";
import Head from "next/head";

import ListData from "@components/ListData";
import Button from "react-bootstrap/Button";
import { useCallback, useState } from "react";
import useData from "@features/useData";
import AddTodo from "@components/AddTodo";

const Todos = () => {
	const dispatch = useDispatch();
	const router = useRouter();
	const [isFetching, setIsFetching] = useState(false);

	const logout = (e: any) => {
		e.preventDefault();
		localStorage.removeItem("id");
		dispatch(logout());
		router.push("/");
	};

	return (
		<Container>
			<Head>
				<title>Mock Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Row md={2} xs={1}>
				<Col>
					<AddTodo setIsFetching={setIsFetching} />
				</Col>
				<Col>
					<Container>
						<ListData isFetching={isFetching} setIsFetching={setIsFetching} />
					</Container>
				</Col>
			</Row>
		</Container>
	);
};

export default Todos;
