// @ts-nocheck
import { useRouter } from "next/router";
import { login, logout, fetchUserTodo } from "@features/userSlice";
import { Col, Container, Form, Row } from "react-bootstrap";
import Head from "next/head";

import ListData from "@components/ListData";
import Button from "react-bootstrap/Button";
import AddTodo from "@components/AddTodo";
import { useAppDispatch } from "hooks";

const Todos = () => {
	const dispatch = useAppDispatch();
	const router = useRouter();

	const logout = () => {
		// dispatch(logout());
		localStorage.removeItem("id");
		alert("berhasil logout!");
		router.push("/");
	};

	return (
		<Container>
			<Head>
				<title>Mock Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Row md={2} xs={1}>
				<Col>
					<AddTodo />
				</Col>
				<Col>
					<Container>
						<ListData />
					</Container>
				</Col>
			</Row>
			<br />
			<Button onClick={logout} variant="primary">
				Logout
			</Button>
		</Container>
	);
};

export default Todos;
