import { useDispatch } from "react-redux";
import { useRouter } from "next/router";
import { login, logout, fetchUserTodo } from "@features/userSlice";
import { Col, Container, Form, Row } from "react-bootstrap";
import Head from "next/head";

import ListData from "@components/ListData";
import Button from "react-bootstrap/Button";
import { useCallback, useState } from 'react';
import useData from "@features/useData";

const Todos = () => {
	const dispatch = useDispatch();
	const router = useRouter();
	const [todos, setTodos] = useState("");
	const [refresh, setRefresh] = useState(false);

	useCallback(() => {
		
	}, [refresh])

	const tambahTodo = async () => {
		const kirimData = await fetch("http://localhost:3000/todo/todos", {
			method: "POST",
			body: JSON.stringify(todos),
		});

		if(kirimData.status === 200) {
			
		}
	}

	const logout = (e: any) => {
		e.preventDefault();
		localStorage.removeItem("id");
		dispatch(logout());
		router.push("/");
	};

	return (
		<Container>
			<Head>
				<title>Mock Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Row md={2} xs={1}>
				<Col>
					<h2 style={{ textAlign: "center" }}>Add Todo</h2>
					<Form>
						<Form.Group>
							<Form.Label>Todo</Form.Label>
							<Form.Control
								type="text"
								required
								maxLength={50}
								minLength={3}
								placeholder={"input your todo"}
								onChange={(e)=> {setTodos(e.target.value)}}
							/>
						</Form.Group>
						<br />
						<Button variant="success" type="submit">
							Add Todo
						</Button>
					</Form>
				</Col>
				<Col>
					<Container>
						<ListData />
					</Container>
				</Col>
			</Row>
		</Container>
	);
};

export default Todos;
